apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 30001          # NodePort exposed on the host
      targetPort: 8080     # Container port for Tomcat
  type: NodePort
